// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetHomeDir():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function NewFile():Promise<main.FileData>;

export function OpenFile(arg1:string):Promise<main.FileData>;

export function OpenFileDialog():Promise<main.FileData>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SaveFileAs(arg1:string,arg2:string):Promise<main.FileData>;

export function SaveFileDialog(arg1:string):Promise<main.FileData>;
